# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

variables:
  - name: storageAccountName
    value: rakesh
pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'Visual Studio Enterprise Subscription – MPN(d2413346-1d72-4ae7-8969-64fbdf906cf8)'
    subscriptionId: 'd2413346-1d72-4ae7-8969-64fbdf906cf8'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'StorageResGrp'
    location: 'East US'
    templateLocation: 'Linked artifact'
    csmFile: './storageacct.json'
    csmParametersFile: './parameter.json'
    deploymentMode: 'Incremental'

- task: AzureCLI@2
  inputs:
    azureSubscription: 'Visual Studio Enterprise Subscription – MPN(d2413346-1d72-4ae7-8969-64fbdf906cf8)'
    scriptType: 'pscore'
    scriptLocation: 'inlineScript'
    inlineScript: |
      $saContext = (Get-AzureRmStorageAccount -ResourceGroupName StorageResGrp -Name rakeshggk1).Context 
      New-AzureStorageTable –Name rakeshtablestore –Context $saContext